### ISSUE TITLE
Merging this repository together with designator_integration

### ISSUE THREAD

**Issue by airballking** [code-iai/designator_integration_lisp#1]
@fairlight1337 Does it make sense to merge this repository together with ```designator_integration```? 

Both depend (almost) only on the respective compilers and ```designator_integration_msgs```, they are closely related, and the lisp compilation does not interfere much with the ```catkin_make``` process. 

Benefit: Would reduce the number of our repository by one.

I would volunteer to provide the pull request.

**Comment by fairlight1337** [comment]
In theory, sure. Do you know whether it would break anything else?
Like the idea

**Comment by gaya-** [comment]
Is this done yet? Can we get rid of this repo? It's confusing.

**Comment by fairlight1337** [comment]
This was solved here: https://github.com/code-iai/designator_integration/pull/2
Closing the issue.
